### PR TITLE
Add conditional 'extern "C"' declarations for C++ compatibility.

### PR DESCRIPTION
**Pull request by bullestock**
This patch makes the library usable from C++ by adding conditional `extern "C"` declarations to the header files.

### CODE REVIEW

**Comment by nopnop2002** [comment]
I have never used C++ with ESP-IDF.

Please tell me how to use C++.

**Comment by nopnop2002** [comment]
There is no answer. so I close this PR.

**Comment by Yanichar** [comment]
> Please tell me how to use C++.

1. Rename main.c to main.cpp
2. Change reference to it in CmakeList.txt
3. Change "void app_main(void)" to "extern "C" void app_main(void)"

Thats all, now you are in the C++ mode. You will probably need some FreeRtos task wraper to use it in C++ mode, I use this solution https://www.freertos.org/FreeRTOS_Support_Forum_Archive/July_2010/freertos_Is_it_possible_create_freertos_task_in_c_3778071.html

This is very userful PR, BTW

**Comment by bullestock** [comment]
Sorry, somehow I never saw the comments from @nopnop2002. But @Yanichar is correct, that is exactly what you do.

My task functions are just global functions with "C" linkage, I don't use member functions as tasks.

**Comment by nopnop2002** [comment]
@bullestock 

It's been a long time, but if you still need a PR, please send it again.

**Pull request closed without merging**
